image: node:12.12-alpine

variables:
  YARN_CACHE_FOLDER: ./yarn
#   DOCKER_HOST: tcp://docker:2375/
#   DOCKER_DRIVER: overlay2

# services:
#   - docker:dind

stages:
  - install
  - build
  - build-image
  - deploy

install:
  stage: install
  cache:
    paths:
      - yarn
  artifacts:
    paths:
      - node_modules
  script: yarn install --frozen-lockfile --production=false

build:
  stage: build
  dependencies:
    - install
  artifacts:
    paths:
      - .build
  script: COMMIT_SHA=${CI_COMMIT_SHORT_SHA} yarn build

typecheck:
  stage: build
  dependencies:
    - install
  script: yarn typecheck

prettier:
  stage: build
  dependencies:
    - install
  script: yarn prettier

lint:
  stage: build
  dependencies:
    - install
  script: yarn lint

audit:
  stage: build
  dependencies:
    - install
  script: yarn audit

test:
  stage: build
  dependencies:
    - install
  script: yarn test

docker-build:
  image: docker:stable
  stage: build-image
  only:
    - master
    - tags
  dependencies:
    - build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --build-arg "CI_COMMIT_SHA=${CI_COMMIT_SHA}" --build-arg "CI_COMMIT_TAG=${CI_COMMIT_TAG}" --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
